name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1.0.1
        with:
          # Container registry username
          username: ${{secrets.ACR_USER}}
          password: ${{secrets.ACR_PASSWORD}}
          # Container registry server url
          login-server: ${{secrets.ACR_LOGIN}}
